kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
    name: {{ .Release.Name }}-service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
