env: prd
datadog: true
image:
  name: "ghcr.io/ledgerhq/knowledge_bot"
  pullSecret: "github-ledgerhq"
  tag: "v1.68.1"

hpa:
  enabled: true
  maxReplicas: 5
  minReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

host: "knowlbot.aws.prd.ldg-tech.com"
whitelistSourceRange: "37.58.221.152/32, 77.158.138.66/32, 37.58.221.154/32, 77.158.138.67/32, 34.240.150.212/32, 52.50.31.80/32"
#serverSnippet:
#  nginx.ingress.kubernetes.io/server-snippet: |
#    set $X-Forwarded-For $X-Original-Forwarded-For;
#    rewrite foo bar permanent;
port: 80
livenessProbePath: "/_health"
readinessProbePath: "/_health"

environment:
  - name: DD_LOGS_INJECTION
    value: "true"
  - name: DD_PROFILING_ENABLED
    value: "false"
  - name: DD_JMXFETCH_ENABLED
    value: "true"
  - name: DD_RUNTIME_METRICS_ENABLED
    value: "true"
  - name: DD_TRACE_AGENT_PORT
    value: "8126"

resources:
  requests:
    memory: "400Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "750m"

external-secrets:
  env-file:
    data:
      - key: knowledge-bot-prd/env-file
        name: .env
  github-ledgerhq:
    data:
      - key: infra/dockerconfigjson-github-com/v01
        name: .dockerconfigjson
    template:
      type: kubernetes.io/dockerconfigjson
