name: docker

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit short SHA
        run: echo "short_sha=${GITHUB_SHA:0:7}" >> ${GITHUB_ENV}

      - name: Get branch tag
        run: echo "branch_tag=${GITHUB_REF_NAME//\//-}" >> ${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CI_BOT_USERNAME }}
          password: ${{ secrets.CI_BOT_TOKEN }}

      - name: Get Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/ledgerhq/knowledge_bot

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/ledgerhq/knowledge_bot:${{ steps.meta.outputs.version }}
          cache-to: type=inline
