{{- range $name, $_ := index .Values "external-secrets" }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  backendType: secretsManager
  {{- if .data }}
  data:
    {{- toYaml .data | nindent 4 }}
  {{- end }}
  {{- if .dataFrom }}
  dataFrom:
    {{- toYaml .dataFrom | nindent 4 }}
  {{- end }}
  {{- if .template }}
  template:
    {{- toYaml .template | nindent 4 }}
  {{- end }}
{{- end }}
